title: 3BC
description: >- 
  Low level language, tiny virtual machine that works on computers and microcontrollers.
  (Friendly Punched cards)
baseurl: "/"
url: "https://3bc-lang.org"

plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-github-metadata
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false


layouts_dir: docs/_layouts/

exclude:
  - src/
  - tests/
  - examples/
  - .sass-cache/
  - .jekyll-cache/
  - main.c
  - Gemfile
  - Gemfile.lock
  - library.properties
  - Makefile
